#!/usr/bin/env bash
# Bash script to gracefully start gunicorn

# Extract the main PID of the Gunicorn service
MAIN_PID=$(systemctl status gunicorn | sed -n 's/.*Main PID: \(.*\)$/\1/g p' | cut -f1 -d' ')

# Send a HUP signal to the main PID to gracefully reload Gunicorn
kill -HUP "$MAIN_PID"
